[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Alex Blood"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
axum-util = "0.2.2"
hyper = "0.14.27"
rusqlite = "0.29.0"
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
tokio = {version = "1.33.0", features = ["full"]}
