[workspace]
resolver = "2"
members = [
    "rust-micro-cms",
    "front-end",
]

[workspace.dependencies]
anyhow = "1.0.81"
axum = "0.7.5"
chrono = "0.4.35"
serde = "1.0.197"
serde_json = "1.0.114"
simple-log = "1.6.0"
sqlx = "0.7.4"
tokio = "1.36.0"
