[package]
name = "backend"
version = "0.1.0"
edition = "2021"
authors = ["Alex Blood"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
